### ISSUE TITLE
按键相关的代码

### ISSUE THREAD

**Issue by earth-hotfix** [waganaha66/CSGO-ESP-Simple-Tuorial#2]
大佬可以说一下这个全局热键是如何实现的吗

**Comment by ryuryu0x08** [comment]
user32.dll
RegisterHotKey()

**Comment by earth-hotfix** [comment]
> user32.dll
> RegisterHotKey()

好像没有看到相关的实现呀

**Comment by ryuryu0x08** [comment]
本来是用D3D开功能菜单注册热键, 由于一部分原因, 换成简单的EDI了, 也删了代码, 你要实现自己调用这个函数一下就实现了, 调用个函数的事情
