### ISSUE TITLE
想请教一个问题?

### ISSUE THREAD

**Issue by zi0n8** [waganaha66/CSGO-ESP-Simple-Tuorial#3]
我看了作者的代码，但是没有找到读取自身xyz的地方，是作者没有写这个吗

**Comment by ryuryu0x08** [comment]
肯定是有读取自身xyz的, 这个方框透视是用ViewMatrix的, 没有自己和敌人距离没法算方框大小, 一定是有的. 这是2年前写的东西了具体细节我也记不太清了.
